### ISSUE TITLE
express.js router API compatibility layer

### ISSUE THREAD

**Issue by tyv** [nodules/susanin#40]
For default router replacement.

**Comment by kaero** [comment]
@ruslankerimov What do you think? Can we provide express.js router API directly or using some decorator?

**Comment by ruslankerimov** [comment]
Why not? Let's try!

**Comment by kaero** [comment]
:calendar: 
![image](https://cloud.githubusercontent.com/assets/352609/12481044/a404cbdc-c057-11e5-8ec9-f0a0544fc9d7.png)

**Comment by kaero** [comment]
Let's do or close this!

**Comment by VodkaBears** [comment]
ok, i'll take a look soon.

**Comment by VodkaBears** [comment]
1. I don't think it should be a part of the repo.
2. It is not so hard to implement a specific middleware yourself. Look at the react-router example, they have the same approach with a server rendering: https://github.com/reactjs/react-router/blob/latest/docs/guides/ServerRendering.md#server-rendering. Benefits: you get more control over your code.
3. This follows on logically from the previous paragraph: we should define a permanent data structure for routes if someone is going to use it in conjunction.
4. The purpose of Susanin is not to handle urls but to provide data to handle them.

**Comment by kaero** [comment]
> The purpose of Susanin is not to handle urls but to provide data to handle them.

The Only Good Reason.
