### ISSUE TITLE
Removing duplicate slashes

### ISSUE THREAD

**Issue by yekver** [nodules/susanin#43]
According to basic principals of URL normalization, duplicate slashes must be removed. If we don't want modify source URL, duplicate slashed must be ignored.

Examples:
```
http://www.яндекс.рф/////index.php
http://www.яндекс.рф///index////subdir////
http://www.яндекс.рф///index//..//../subfile
```

Expected output:
```
http://www.яндекс.рф/index.php
http://www.яндекс.рф/index/subdir/
http://www.яндекс.рф/index/subfile
```

**Comment by kaero** [comment]
> According to basic principals of URL normalization, duplicate slashes must be removed.

According to [section 6 of RFC 3986 "Uniform Resource Identifier (URI): Generic Syntax"](https://tools.ietf.org/html/rfc3986#section-6) – not.

**Comment by golyshevd** [comment]
@yekver You can normalize urls using upper proxy server

http://nginx.org/en/docs/http/ngx_http_core_module.html#location
