### ISSUE TITLE
Зачем парсятся GET параметры из урла?

### ISSUE THREAD

**Issue by 4ok** [nodules/susanin#45]
Они на самом деле мешают и вообще они мне не нужны в параметрах роутера. А если и будут нужны, то можно использовать другой модуль для их парсинга, например connect-query. Вообщем мне не нравится идея, что параметры GET и роутера смешаны. Хочется явно брать параметры из GET, POST или URL (susanin).

2) Хотелось бы иметь возможность получить имя паттерна по которому был найден модуль, сейчас он лежит приватно тут — _options.pattern и вдобавок он какой-то грязный (всякие скобочки и т.п)

**Comment by ruslankerimov** [comment]
1) Используй опцию `userQueryString: false`, [демо](http://nodul.es/susanin/#%7B%0A%20%20%20%20pattern%3A%20'%2Fjeans(%2F%3Cbrand%3E(%2F%3Cid%3E))'%2C%0A%20%20%20%20useQueryString%3A%20false%0A%7D%3A%3A'%2Fjeans%2Flevis%2F1234%3Ffoo%3Dbla'%3A%3A%7B%0A%20%20%20%20brand%3A%20'levis'%2C%0A%20%20%20%20foo%3A%20'bla'%0A%7D%3A%3A1.0.1%3A%3A%3A%3Afalse);
2) Зачем интересно тебе патттерн? Если всё таки нужен, то положи его в опцию `data` и сможешь получить   через `route.getData()`, [демо](http://nodul.es/susanin/#%7B%0A%20%20%20%20pattern%3A%20'%2Fjeans(%2F%3Cbrand%3E(%2F%3Cid%3E))'%2C%0A%20%20%20%20data%3A%20%7B%0A%20%20%20%20%20%20%20%20pattern%3A%20'%2Fjeans(%2F%3Cbrand%3E(%2F%3Cid%3E))'%0A%20%20%20%20%7D%0A%7D%3A%3A%3A%3A%3A%3A1.0.1%3A%3A%3A%3Afalse).

**Comment by 4ok** [comment]
:+1:
